<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * View reports generated by automation rules on screen, with a download
 * link. With no parameter it lists every saved report; with ?file=NAME
 * it renders that one report as a table.
 *
 * @package    tool_automate
 * @copyright  2026 verzog <verzog@gmail.com>
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

require(__DIR__ . '/../../../config.php');
require_once($CFG->libdir . '/adminlib.php');

admin_externalpage_setup('tool_automate');
$context = context_system::instance();
require_capability('tool/automate:manage', $context);

$file = optional_param('file', '', PARAM_FILE);

$baseurl = new moodle_url('/admin/tool/automate/report.php');
$PAGE->set_url($baseurl, $file !== '' ? ['file' => $file] : []);
$PAGE->set_title(get_string('savedreports', 'tool_automate'));
$PAGE->set_heading(get_string('savedreports', 'tool_automate'));
$PAGE->add_body_class('tool_automate-page');

$fs = get_file_storage();

echo $OUTPUT->header();
echo html_writer::link(
    new moodle_url('/admin/tool/automate/index.php'),
    get_string('back', 'tool_automate'),
    ['class' => 'tool_automate_back']
);

if ($file !== '') {
    // Render a single report. PARAM_FILE plus the fixed
    // component/area/itemid/path means there's no path-traversal surface.
    $stored = $fs->get_file($context->id, 'tool_automate', 'reports', 0, '/', $file);
    if (!$stored || $stored->is_directory()) {
        echo $OUTPUT->notification(get_string('reportgone', 'tool_automate'), 'error');
        echo $OUTPUT->footer();
        exit;
    }

    echo $OUTPUT->heading(s($file), 3);

    $downloadurl = moodle_url::make_pluginfile_url(
        $context->id,
        'tool_automate',
        'reports',
        0,
        '/',
        $file,
        true
    );
    echo $OUTPUT->single_button(
        $downloadurl,
        get_string('downloadreport', 'tool_automate'),
        'get'
    );

    $content = $stored->get_content();
    if (substr(strtolower($file), -4) === '.csv') {
        // Parse the CSV through a stream so quoted fields with embedded
        // commas or newlines are handled correctly.
        $rows = [];
        $fh = fopen('php://temp', 'r+');
        fwrite($fh, $content);
        rewind($fh);
        while (($row = fgetcsv($fh)) !== false) {
            $rows[] = $row;
        }
        fclose($fh);

        if ($rows) {
            $table = new html_table();
            $table->attributes['class'] = 'generaltable tool_automate_report';
            $table->head = array_shift($rows);
            foreach ($rows as $row) {
                $table->data[] = array_map('s', $row);
            }
            echo html_writer::table($table);
        } else {
            echo $OUTPUT->notification(get_string('reportempty', 'tool_automate'), 'info');
        }
    } else {
        echo html_writer::tag('pre', s($content), ['class' => 'tool_automate_report_text']);
    }

    echo $OUTPUT->footer();
    exit;
}

// No file requested: list every saved report, newest first.
$files = $fs->get_area_files($context->id, 'tool_automate', 'reports', 0, 'timecreated DESC', false);
if (!$files) {
    echo $OUTPUT->notification(get_string('noreports', 'tool_automate'), 'info');
    echo $OUTPUT->footer();
    exit;
}

$table = new html_table();
$table->head = [
    get_string('reportfile', 'tool_automate'),
    get_string('when', 'tool_automate'),
    get_string('reportsize', 'tool_automate'),
    get_string('actions', 'tool_automate'),
];
foreach ($files as $stored) {
    $name = $stored->get_filename();
    $viewurl = new moodle_url($baseurl, ['file' => $name]);
    $downloadurl = moodle_url::make_pluginfile_url(
        $context->id,
        'tool_automate',
        'reports',
        0,
        '/',
        $name,
        true
    );
    $links = html_writer::link($viewurl, get_string('viewreport', 'tool_automate'))
        . ' | '
        . html_writer::link($downloadurl, get_string('downloadreport', 'tool_automate'));
    $table->data[] = [
        html_writer::link(new moodle_url($baseurl, ['file' => $name]), s($name)),
        userdate($stored->get_timecreated()),
        display_size($stored->get_filesize()),
        $links,
    ];
}
echo html_writer::table($table);

echo $OUTPUT->footer();
